name: Go

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        go:
          - '1.11'
          - '1.12'
          - '1.13'
          - '1.14'
          - '1.15'
          - '1.16'
          - '1.17'

    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '${{ matrix.go }}'

      - name: 'Build'
        run: go build -v ./...

      - name: 'Test'
        run: go test -v ./...

      - name: 'Vet'
        run: go vet ./...

      - name: 'Staticcheck'
        # staticcheck requires go1.14.
        if: ${{ matrix.go != '1.11' && matrix.go != '1.12' && matrix.go != '1.13' }}
        run: |
          go get honnef.co/go/tools/cmd/staticcheck
          staticcheck ./...
